name: Checkmarx AST Github Action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@2.0.7
        with:
          project_name: ${{ github.repository }}
          cx_tenant: beta_nova8
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
